{% set name = "cargo-make" %}
{% set version = "0.37.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sagiegurari/cargo-make/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4d2cdf575715f19ccc0c362244f1d2f37709866aa4c147b7d282c047c1ebec31

build:
  binary_relocation: false
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
  run:

test:
  commands:
    - test -f $PREFIX/bin/cargo-make  # [unix]
    - test -f $PREFIX/bin/makers  # [unix]
    - if not exist %CONDA_PREFIX%\Scripts\cargo-make.exe exit 1  # [win]
    - if not exist %CONDA_PREFIX%\Scripts\makers.exe exit 1  # [win]
    - cargo-make -h
    - makers -h

about:
  home: https://github.com/sagiegurari/cargo-make
  summary: 'Rust task runner and build tool.'
  description: |
    The cargo-make task runner enables to define and configure sets of tasks and run them as a flow.
    A task is a command, script, rust code, or other sub tasks to execute.
    Tasks can have dependencies which are also tasks that will be executed before the task itself.
    With a simple toml based configuration file, you can define a multi platform build script that
    can run build, test, generate documentation, run bench tests, run security validations and more,
    executed by running a single command.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  doc_url: https://sagiegurari.github.io/cargo-make/

extra:
  recipe-maintainers:
    - MementoRC
