{% set name = "cargo-make" %}
{% set version = "0.37.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sagiegurari/cargo-make/archive/refs/tags/{{ version }}.tar.gz
  sha256: 954ba24bd4aaf3e731e8bb4601e94cf491397bb394c1a71ef0908530477b62fc

build:
  binary_relocation: false
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
  run:

test:
  commands:
    - cargo-make --help
    - makers --help

about:
  home: https://github.com/sagiegurari/cargo-make
  summary: 'Rust task runner and build tool.'
  description: |
    The cargo-make task runner enables to define and configure sets of tasks and run them as a flow.
    A task is a command, script, rust code, or other sub tasks to execute.
    Tasks can have dependencies which are also tasks that will be executed before the task itself.
    With a simple toml based configuration file, you can define a multi platform build script that
    can run build, test, generate documentation, run bench tests, run security validations and more,
    executed by running a single command.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

  doc_url: https://sagiegurari.github.io/cargo-make/

extra:
  recipe-maintainers:
    - MementoRC
